# SPDX-FileCopyrightText: 2024-2026 Mag329
#
# SPDX-License-Identifier: MIT

- key: enable_new_mark_notification
  label: Показывать уведомления о новых оценках
  type: bool
  ordering: 1
  visible: true
  experimental: false

- key: enable_homework_notification
  label: Показывать уведомления о новых домашних заданиях
  type: bool
  ordering: 2
  visible: true
  experimental: false

- key: skip_empty_days_schedule
  label: Не отображать в расписании дни без уроков
  type: bool
  ordering: 3
  visible: true
  experimental: false

- key: skip_empty_days_homeworks
  label: Пропускать в списке домашних заданий дни без заданий
  type: bool
  ordering: 4
  visible: true
  experimental: false

- key: next_day_if_lessons_end_schedule
  label: Автоматически показывать расписание на следующий день, если сегодня уроки уже закончились
  type: bool
  ordering: 5
  visible: true
  experimental: false

- key: next_day_if_lessons_end_homeworks
  label: Автоматически показывать домашние задания на следующий день, если сегодня уроки уже закончились
  type: bool
  ordering: 6
  visible: true
  experimental: false

- key: enable_homework_done_function
  label: Включить возможность отметить ДЗ как выполненное 
  type: bool
  ordering: 7
  visible: true
  experimental: false

- key: experimental_features
  label: Включить экспериментальные функции
  type: bool
  ordering: 8
  visible: true
  experimental: false

- key: use_cache
  label: Использовать кэширование для запросов
  type: bool
  ordering: 1
  visible: false
  experimental: true