# SPDX-FileCopyrightText: 2024-2026 Mag329
#
# SPDX-License-Identifier: MIT

- name: day
  title: день
  text_name: 1 день
  price: 5
  duration: 1
  ordering: 1
  show_in_menu: true

- name: week
  title: неделя
  text_name: 1 неделю
  price: 30
  duration: 7
  ordering: 2
  show_in_menu: true

- name: month
  title: месяц
  text_name: 1 месяц
  price: 100
  duration: 30
  ordering: 3
  show_in_menu: true

- name: year
  title: год
  text_name: 1 год
  price: 1000
  duration: 365
  ordering: 4
  show_in_menu: true

- name: 3_days
  title: 3 дня
  text_name: 3 дня
  price: -1
  duration: 3
  ordering: -1
  show_in_menu: false